import Joi from 'joi';

export const employeeFeedbackSchema = Joi.object({
    name: Joi.string().required().messages({
        'string.empty': 'Nome é obrigatório',
    }),
    email: Joi.string().email().required().messages({
        'string.email': 'Email inválido',
        'string.empty': 'Email é obrigatório',
    }),
    corporateEmail: Joi.string().email().required().messages({
        'string.email': 'Email inválido',
        'string.empty': 'Email é obrigatório',
    }),
    department: Joi.string().required(),
    jobRole: Joi.string().required(),
    jobFunction: Joi.string().required(),
    location: Joi.string().required(),
    companyTenure: Joi.string().required(),
    gender: Joi.string().required(),
    generation: Joi.string().required(),
    level0Company: Joi.string().required(),
    level1Directorate: Joi.string().required(),
    level2Management: Joi.string().required(),
    level3Coordination: Joi.string().required(),
    level4Area: Joi.string().required(),
    responseDate: Joi.date().required(),
    jobInterest: Joi.number().required(),
    jobInterestComments: Joi.string().required(),
    contribution: Joi.number().allow(null).optional(),
    contributionComments: Joi.string().allow(null, '').optional(),
    learningDevelopment: Joi.number().required(),
    learningDevelopmentComments: Joi.string().allow(null, '').optional(),
    feedbackScore: Joi.number().allow(null).optional(),
    feedbackComments: Joi.string().allow(null, '').optional(),
    managerInteraction: Joi.number().allow(null).optional(),
    managerInteractionComments: Joi.string().allow(null, '').optional(),
    careerClarity: Joi.number().required(),
    careerClarityComments: Joi.string().allow(null, '').optional(),
    permanenceExpectation: Joi.number().allow(null).optional(),
    permanenceExpectationComments: Joi.string().allow(null, '').optional(),
    enpsScore: Joi.number().allow(null).optional(),
    enpsOpenComments: Joi.string().allow(null, '').optional(),
});
